backend:
  name: git-gateway
  branch: main

media_folder: "public/assets/property"
public_folder: "/assets/property"

collections:
  - name: "property"
    label: "Property"
    folder: "src/property"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Area", name: "area", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Cover Image", name: "image", widget: "image" }
      - { label: "Youtube Video Link", name: "video", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
